version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    ports: ["8000:8000"]
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    environment:
      - BACKEND_URL=http://backend:8000
    ports: ["8501:8501"]
    depends_on: [backend]
